### ISSUE TITLE
(Suggestion) MIT License?

### ISSUE THREAD

**Issue by htv04** [globalcitizen/svglover#10]
I recently found out about svglover, and it is a very useful library. I'm looking to use it in some of my projects and make a fork to help continue development. However, I noticed that it's licensed under the GPL v3 license, which requires projects that use the library to release their source code. I often release the source code of projects I work on, but there are some cases where I would rather keep my source code proprietary. Could you consider relicensing svglover under a more permissive license like the MIT license?

I apologize if this has been asked or addressed already, I didn't see anything about this on the repo.

**Comment by globalcitizen** [comment]
Sorry, multiple contributors, not viable to change license.

**Comment by htv04** [comment]
Oh ok, thanks for letting me know.
